-- KEY=AUTHOR_ID, BOOK_ID
WITH SALES AS (SELECT B.PRICE * S.CNT TOTAL_SALES, B.AUTHOR_ID AID, B.CATEGORY 
           FROM BOOK B
           LEFT JOIN (SELECT SUM(SALES) CNT, BOOK_ID FROM BOOK_SALES 
                      WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31' GROUP BY BOOK_ID) S
           ON S.BOOK_ID = B.BOOK_ID)
           
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, S.CATEGORY, SUM(S.TOTAL_SALES)
FROM SALES S
RIGHT JOIN AUTHOR A
ON S.AID = A.AUTHOR_ID
GROUP BY S.AID, S.CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;
               


