SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID NOT IN (SELECT DISTINCT PARENT_ITEM_ID 
                      FROM ITEM_TREE
                     WHERE PARENT_ITEM_ID IS NOT NULL) # NULL 제외해줘야 제대로 NOT IN 처리됨
ORDER BY ITEM_ID DESC;

# SELECT DISTINCT PARENT_ITEM_ID FROM ITEM_TREE;