-- 대여 금액 내림차순, 자동차 종류 오름차순, 자동차 아이디 내림차순
SELECT C.CAR_ID, C.CAR_TYPE, ROUND(C.DAILY_FEE * (1- (DP.DISCOUNT_RATE*0.01)) * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
LEFT JOIN (SELECT CAR_TYPE, DURATION_TYPE, DISCOUNT_RATE
           FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
           WHERE DURATION_TYPE = '30일 이상') DP
ON C.CAR_TYPE = DP.CAR_TYPE
WHERE CAR_ID NOT IN(SELECT CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01') AND
      C.CAR_TYPE IN ('SUV', '세단') AND
      C.DAILY_FEE * (1- (DP.DISCOUNT_RATE*0.01)) * 30 BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;