-- 대여 금액 내림차순, 자동차 종류 오름차순, 자동차 아이디 내림차순
WITH T AS (SELECT CAR_ID, C.CAR_TYPE CAR_TYPE, ROUND(C.DAILY_FEE * (1- (DP.DISCOUNT_RATE*0.01)) * 30) AS FEE
            FROM CAR_RENTAL_COMPANY_CAR AS C
            LEFT JOIN (SELECT CAR_TYPE, DURATION_TYPE, DISCOUNT_RATE
                       FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                       WHERE DURATION_TYPE = '30일 이상') DP
            ON C.CAR_TYPE = DP.CAR_TYPE
            WHERE CAR_ID NOT IN(SELECT CAR_ID
                                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                                WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01') AND
                  C.CAR_TYPE IN ('SUV', '세단'))
                  
SELECT CAR_ID, CAR_TYPE, FEE
FROM T
WHERE FEE BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;