WITH MF AS (SELECT FOOD_TYPE FT, MAX(FAVORITES) FAV
     FROM REST_INFO
     GROUP BY FOOD_TYPE)
     
SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES
FROM REST_INFO R
RIGHT JOIN MF
ON R.FAVORITES = MF.FAV AND R.FOOD_TYPE = MF.FT
ORDER BY FOOD_TYPE DESC;