SELECT USER_ID, NICKNAME, CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) '전체주소',
        CONCAT(SUBSTRING(TLNO, 1, 3), '-', SUBSTRING(TLNO, 4, 4), '-', SUBSTRING(TLNO, 8, 4)) '전화번호'
FROM USED_GOODS_USER A
JOIN ( SELECT WRITER_ID, COUNT(*) CNT
        FROM USED_GOODS_BOARD
        GROUP BY WRITER_ID
        HAVING CNT >= 3) B
ON A.USER_ID = B.WRITER_ID
ORDER BY USER_ID DESC;

