SELECT T.CAR_ID, ROUND(AVG(T.DURATION), 1) AS AVERAGE_DURATION
FROM (select CAR_ID, DATEDIFF(END_DATE, START_DATE) + 1 AS DURATION
      from CAR_RENTAL_COMPANY_RENTAL_HISTORY) T
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;

