


SELECT COUNT(*) AS FISH_COUNT, T.FN AS FISH_NAME
FROM (
    SELECT B.FISH_NAME AS FN
    FROM FISH_INFO A
    LEFT JOIN FISH_NAME_INFO B
    ON A.FISH_TYPE = B.FISH_TYPE
) AS T
GROUP BY T.FN
ORDER BY FISH_COUNT DESC;
