SET @userCnt := (SELECT count(*) FROM USER_INFO WHERE DATE_FORMAT(JOINED, '%Y') = '2021');

WITH T AS (SELECT DISTINCT DATE_FORMAT(SALES_DATE, '%Y') YEAR, DATE_FORMAT(SALES_DATE, '%m') MONTH, USER_ID, JOINED
           FROM ONLINE_SALE
           LEFT JOIN USER_INFO
           USING (USER_ID)
           WHERE DATE_FORMAT(JOINED, '%Y') = '2021')

SELECT YEAR, MONTH, COUNT(*) PUCHASED_USERS, ROUND(COUNT(*) / @userCnt, 1) AS PUCHASED_RATIO
FROM T
group by YEAR, MONTH
ORDER BY YEAR, MONTH;
