WITH HV_USER AS (SELECT HOST_ID, COUNT(*) CNT
                FROM PLACES
                GROUP BY HOST_ID
                HAVING CNT > 1)
SELECT *
FROM PLACES
WHERE HOST_ID IN (SELECT HOST_ID FROM HV_USER)
ORDER BY ID;