WITH T AS (SELECT C.CAR_TYPE, HISTORY_ID, DATEDIFF(END_DATE, START_DATE)+1 AS DIFF, 
           CASE 
               WHEN DATEDIFF(END_DATE, START_DATE)+1 < 7 THEN 0
               WHEN DATEDIFF(END_DATE, START_DATE)+1 < 30 THEN 7
               WHEN DATEDIFF(END_DATE, START_DATE)+1 < 90 THEN 30
               ELSE 90
          END AS DISCNT,
          DAILY_FEE
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
          LEFT JOIN CAR_RENTAL_COMPANY_CAR C
          USING (CAR_ID)
          WHERE CAR_TYPE = '트럭')
          
SELECT HISTORY_ID, ROUND(IF(DISCOUNT_RATE IS NULL, DIFF * DAILY_FEE, DAILY_FEE * (1-DISCOUNT_RATE*0.01) * DIFF)) FEE
FROM T
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON T.CAR_TYPE = P.CAR_TYPE AND P.DURATION_TYPE LIKE CONCAT(T.DISCNT , '%')
ORDER BY FEE DESC, HISTORY_ID DESC;

