WITH RECURSIVE T AS (SELECT 0 AS HOUR
                     UNION ALL
                     SELECT HOUR + 1
                     FROM T WHERE HOUR < 23)
SELECT T.HOUR, IFNULL(A.CNT, 0) COUNT
FROM T 
LEFT JOIN (SELECT DATE_FORMAT(DATETIME, '%H') HOUR, COUNT(*) CNT
           FROM ANIMAL_OUTS 
           GROUP BY HOUR) A
ON T.HOUR = A.HOUR
ORDER BY T.HOUR
