SELECT BOARD.UID USER_ID, USERS.NICKNAME, BOARD.TOTAL_SALES
FROM USED_GOODS_USER USERS
RIGHT JOIN (SELECT WRITER_ID UID, SUM(PRICE) TOTAL_SALES
            FROM USED_GOODS_BOARD
            WHERE STATUS = 'DONE' 
            GROUP BY UID
            HAVING TOTAL_SALES >= 700000) BOARD
ON USERS.USER_ID = BOARD.UID
ORDER BY BOARD.TOTAL_SALES;