WITH MOST AS (SELECT MEMBER_ID, COUNT(*) CNT
              FROM REST_REVIEW
              GROUP BY MEMBER_ID
              ORDER BY CNT DESC
              LIMIT 1)
              
SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM REST_REVIEW R
LEFT JOIN MEMBER_PROFILE M
ON R.MEMBER_ID = M.MEMBER_ID
LEFT JOIN MOST
ON R.MEMBER_ID = MOST.MEMBER_ID
WHERE R.MEMBER_ID = MOST.MEMBER_ID
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT;