WITH MAX_TYPE_LENGTH AS (
    SELECT FISH_TYPE, MAX(LENGTH) AS LEN
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)

SELECT B.ID, C.FISH_NAME, B.LENGTH
FROM MAX_TYPE_LENGTH A
LEFT JOIN FISH_INFO B
ON A.FISH_TYPE = B.FISH_TYPE 
    AND A.LEN = B.LENGTH
LEFT JOIN FISH_NAME_INFO C
ON B.FISH_TYPE = C.FISH_TYPE
ORDER BY B.ID;