-- PUB_DATE = 2021 && CATEGORY = '인문' / 도서 ID, 출판일 출력 / 출판일 기준 오름차순
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK
WHERE  DATE_FORMAT(PUBLISHED_DATE, '%Y') = '2021' AND  CATEGORY = '인문'
ORDER BY PUBLISHED_DATE ASC;