WITH T AS (SELECT D.DEPT_ID, D.DEPT_NAME_EN, AVG(SAL) AVG_SAL
          FROM HR_EMPLOYEES E
          LEFT JOIN HR_DEPARTMENT D
          USING (DEPT_ID)
          GROUP BY DEPT_ID
          ORDER BY AVG_SAL DESC)
          
SELECT DEPT_ID, DEPT_NAME_EN, ROUND(AVG_SAL) AVG_SAL
FROM T;