/* 2022년 1월만, 카테고리 별 도서 판매량 SUM => CATEGORY, TOTAL_SALES 로 출력
- 카테고리 기준 오름차순 정렬
*/

SELECT B.CATEGORY CATEGORY, SUM(BS.SALES) TOTAL_SALES
FROM BOOK_SALES AS BS
LEFT JOIN BOOK B
ON B.BOOK_ID = BS.BOOK_ID
WHERE BS.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY;