WITH MAXPRICE AS (SELECT MAX(PRICE) PRICE
                  FROM FOOD_PRODUCT 
                  WHERE CATEGORY IN ('과자', '국', '김치', '식용유') 
                  GROUP BY CATEGORY)

SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT A
JOIN MAXPRICE
USING (PRICE)
WHERE A.CATEGORY IN ('과자', '국', '김치', '식용유') 
ORDER BY PRICE DESC;