SELECT *
FROM (SELECT 
        CASE
            WHEN EXISTS (SELECT 1 FROM SKILLCODES WHERE CATEGORY = 'Front End' AND SKILL_CODE & CODE > 0)
                AND EXISTS (SELECT 1 FROM SKILLCODES WHERE NAME = 'Python' AND SKILL_CODE & CODE > 0)
            THEN 'A'
            WHEN EXISTS (SELECT 1 FROM SKILLCODES WHERE NAME = 'C#' AND SKILL_CODE & CODE > 0)
            THEN 'B'
            WHEN EXISTS (SELECT 1 FROM SKILLCODES WHERE CATEGORY = 'Front End' AND SKILL_CODE & CODE > 0)
            THEN 'C'
            ELSE NULL
        END AS GRADE,
        ID, EMAIL
    FROM DEVELOPERS) T
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID;